primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  image = "ghcr.io/polyscale/pce:stable"

[env]
  PCE_TAG = "fly-pce"
  PRIMARY_REGION = "iad"

[[services]]
  protocol = "tcp"
  internal_port = 9000

  [[services.ports]]
    port = 3306
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = "tcp"
  internal_port = 9001

  [[services.ports]]
    port = 3307
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = "tcp"
  internal_port = 9010

  [[services.ports]]
    port = 5432
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = "tcp"
  internal_port = 9020

  [[services.ports]]
    port = 1433
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
